# This file was auto-generated by Fern from our API Definition.

from ..core.exceptions.fern_http_exception import FernHTTPException
from ..types.http_validation_error import HttpValidationError


class UnprocessableEntityError(FernHTTPException):
    def __init__(self, error: HttpValidationError):
        super().__init__(status_code=422, name="UnprocessableEntityError", content=error)
